version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/darwin
hooks:
  # BeforeInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root
  # AfterInstall:
  #   - location: shell/install_node_package.sh
  #     timeout: 300
  #     runas: ubuntu
  ApplicationStart:
    - location: shell/start_server.sh
      timeout: 300
      runas: ubuntu
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root
