const cron = require("node-cron");
require('dotenv').config({
    path: '.env'
});
require('../db/connection');

const rabbitMQ = require('../helpers/rabbitMQ');
rabbitMQ.start();
// const Afftrack = require('./apiPlugins/afftrack');
// const Affise = require('./apiPlugins/affise');
// const Fuseclick = require('./apiPlugins/fuseclick');
// const Hasoffer = require('./apiPlugins/hasoffer');
// const Hugoffers = require('./apiPlugins/hugoffers');
// const Offer18 = require('./apiPlugins/offer18');
// const Orangear = require('./apiPlugins/orangear');
// const Orangear_v3 = require('./apiPlugins/orangear_v3');
// const Youmi = require('./apiPlugins/youmi');
// const Tabatoo = require('./apiPlugins/tabatoo');
// const Offerslook = require('./apiPlugins/offerslook');
// const Vinetool = require('./apiPlugins/vinetool');
// const Pentamob = require('./apiPlugins/pentamob');
// const Applift = require('./apiPlugins/applift');
// const Trackier = require('./apiPlugins/trackier');
// const Mobiproud = require('./apiPlugins/mobiproud');
// const Sekomedia = require('./apiPlugins/sekomedia');
// const Trooperads = require('./apiPlugins/trooperads');
// const DofunApps = require('./apiPlugins/dofunapps');
// const Linkgoads = require('./apiPlugins/linkgoads');
// const Occuad = require('./apiPlugins/occuad');
// const Qverseads = require('./apiPlugins/qverseads');
// const Megable = require('./apiPlugins/megable');
// const Adgagaa = require('./apiPlugins/adgagaa');
// const Mobifunadx = require('./apiPlugins/mobifunadx')
// const Gourdmobi = require('./apiPlugins/gourdmobi');
// const Mobikok = require('./apiPlugins/mobikok');
// const WhatsCpi = require('./apiPlugins/whatscpi');
// const Superads = require('./apiPlugins/superads');
// const Appcoachs = require('./apiPlugins/appcoachs');
// const Mobivisits = require('./apiPlugins/mobivisits');
// const Admedx = require('./apiPlugins/admedx');
// const TrackRC = require('./apiPlugins/trackrc');
// const Vortexmedia = require('./apiPlugins/vortexmedia');
// const Mobimelon = require('./apiPlugins/mobimelon');
// const FunnyStore = require('./apiPlugins/funnystore');
// const Zettamobi = require('./apiPlugins/zettamobi');
// const Echo226 = require('./apiPlugins/echo226');
// const Promoadx = require('./apiPlugins/promoadx');
// const Mobusi = require('./apiPlugins/mobusi');
// const Mybestclick = require('./apiPlugins/mybestclick');
// const Cpalock = require('./apiPlugins/cpalock');
// const Mobisummer = require('./apiPlugins/mobisummer');
// const Gowide = require('./apiPlugins/gowide');
// const Artofclick = require('./apiPlugins/artofclick');
// const Cityads = require('./apiPlugins/cityads');
// const Cpology = require('./apiPlugins/cpology');
// const Imocash = require('./apiPlugins/imocash');
// const Mobrain = require('./apiPlugins/mobrain');
// const Instal = require('./apiPlugins/instal');
// const Cake = require('./apiPlugins/cake');
// const AppDiscover = require('./apiPlugins/appdiscover');
// const EverflowClient = require('./apiPlugins/everflowclient');
// const Dailybestapps = require('./apiPlugins/dailybestapps');
// const Persona = require('./apiPlugins/persona');
// const Crunchiemedia = require('./apiPlugins/crunchiemedia');
// const Vene = require('./apiPlugins/vene');
// const Twinkleunion = require('./apiPlugins/twinkleunion');
// const Adsplay = require('./apiPlugins/adsplay');
// const CollectCent = require('./apiPlugins/collectcent');
// const Algambo = require('./apiPlugins/algambo');
// const Apetab = require('./apiPlugins/apetab');
// const AdOn = require('./apiPlugins/adon');
// const Oneway = require('./apiPlugins/oneway');
// const Retail9 = require('./apiPlugins/retail9');
// const Roidynamic = require('./apiPlugins/roiDynamic');
// const Avazu = require('./apiPlugins/avazu');
// const StarmobMedia = require('./apiPlugins/starmobmedia');
// const ResultMedia = require('./apiPlugins/resultmedia');
// const Mobobeat = require('./apiPlugins/mobobeat');
// const Agileadnetwork = require('./apiPlugins/agileadnetwork');
// const Trackrevenue = require('./apiPlugins/trackrevenue');
// const DreamMobi = require('./apiPlugins/dreammobi');
// const Clicks9 = require('./apiPlugins/click9');
// const Auctera = require('./apiPlugins/auctera');
// const Appxigo = require('./apiPlugins/appxigo');
// const Appsilon = require('./apiPlugins/appsilon');
// const Kpmbro = require('./apiPlugins/kpmbro');
// const MocaTech = require('./apiPlugins/mocaTech');
// const Appflood = require('./apiPlugins/appflood');
// const Offershub = require('./apiPlugins/Offershub');
// const Taptica = require('./apiPlugins/taptica');
// const Revlinker = require('./apiPlugins/revlinker');
// const Jinglemobi = require('./apiPlugins/jinglemobi');
// const Skyworker = require('./apiPlugins/Skyworker');
// const Bucksense = require('./apiPlugins/bucksense');
// const Totoroadx = require('./apiPlugins/totoroadx');
// const Mobeetech = require('./apiPlugins/mobeetech');
// const Indexmobi = require('./apiPlugins/indexmobi');
// const Appleads = require('./apiPlugins/appleads');
// const Feeltapmobi = require('./apiPlugins/feeltapmobi');
// const Adbink = require('./apiPlugins/adbink');
// const Trakneo = require('./apiPlugins/trakneo');
// const Hehemobi = require('./apiPlugins/hehemobi');
// const Gadmobe = require('./apiPlugins/gadmobe');
// const Appicmedia = require('./apiPlugins/appicmedia');
// const Informadz = require('./apiPlugins/informadz');
// const Addattain = require('./apiPlugins/addattain');
// const Addotline = require('./apiPlugins/addotline');
// const Gazet = require('./apiPlugins/gazet');
// const Curate = require('./apiPlugins/curate');
// const Adosiz = require('./apiPlugins/adosiz');
// const Mobrand = require('./apiPlugins/mobrand');
// const Pivomob = require('./apiPlugins/pivomob');
// const Gamespipe = require('./apiPlugins/gamespipe');
// const Newseed = require('./apiPlugins/newseed');
// const Clixsad = require('./apiPlugins/clixsad');
// const Seanear = require('./apiPlugins/seanear');
// const Swaarm = require('./apiPlugins/swaarm');
// const Proffcus = require('./apiPlugins/proffcus');
// const Chestnut = require('./apiPlugins/chestnut');
// const Sixpush = require('./apiPlugins/sixpush');
// const Hopemobi = require('./apiPlugins/hopemobi');
// const Vikingmedia = require('./apiPlugins/vikingmedia');
// const Mobilink = require('./apiPlugins/mobilink');
// const Batmobi = require('./apiPlugins/batmobi');
const OfferFetchApi = require('./apiPlugins/offerFetchApi');
const AutoApplyAndPushToWebhook = require('../scripts/autoApplyAndPushToWebhook')   // auto apply and push to webhook from jumbo. 
// currency cron
const currency = require('../scripts/currency');
const applyPlugins = require('./applyPlugins/offerApply');
// const applyPlugins2=require('./applyPlugins/offerApply2')
const wishListUpdate = require('../scripts/hourlyUpdateWishlist');
const wishListFlush = require('../scripts/filterAndDeleteWishlist');
const PackageIdSummary = require('../scripts/appIdSummaryGenerate');
const OfferDelete = require('../scripts/deleteInactiveOffers');
const autoBlockOffer = require('../scripts/autoBlockOffer');


// const createSourceSummary = require('../scripts/createSourceSummary');

const reportsCron = require('../scripts/aggregateSourceSummary');

const scrapingScript = require("../scripts/saveAppIdsForScraping");
const updateScrapingScript = require("../scripts/updateScraping");
const UpdateOffersCountInRedis = require("../scripts/updateOffersCountInRedis");
const dashboard = require("../scripts/dashboard");
const liveReportScript = require("../scripts/liveReport");
const ewtScript = require("../scripts/ewtoffer");
const waitingForApprovalofferSync = require("../scripts/waitingForApprovalofferSync");
const waitingForApprovalofferSync2 = require("../scripts/waitingForApprovalofferSync2");
const EWT_WEBHOOK_TIME_GAP = process.env.EWT_WEBHOOK_TIME_GAP || 5
const advOfferScript=require('../scripts/advOfferReportEachNetwork')
const offersCountByAppId  = require('../scripts/offersCountByAppId');
const live_dashboard_Script = require('../scripts/dashboard2') 
const update_application_status  = require("../scripts/updateApplicationStatus")
const startLiveReportScriptForClickData = require('../scripts/updateLiveAndDailyReports');

let cron_time = "0 */1 * * *";
let report_cron_time = "05,35 * * * *";
let offer_apply_cron_time = "30 */2 * * *";
let wishListUpdateTime = '0 */2 * * * ';
let wishListFlushTime = '30 23 * * *';
let pkgSummaryGenTime = '0 2 * * *';
let offerDeleteTime = '0 */6 * * *';
let scrapingScript_cron_time = "0 3 * * *";
let updateScrapingScript_cron_time = "0 15 * * *";
let dashboard_cron_time = "15,45 * * * *";
let dashboard_live_cron_time = '* * * * *';
let wOfferAutosync_cron_time = "0 */6 * * *";
let wOfferAutosync_cron_time2 = "0 */8 * * *";
let update_application_status_time  = "0 * * * *" ;
let autoBlock_cron_time = "15 * * * *";
let autoApplyAndPushToWebhook_cron_time  = "3 * * * *"
// let cron_time = "* * * * *"; // for local testing
let offersCountByAppId_cron_time = "0 8,10,12,13,15 * * *"  ;
 let advOfferstats_CronTime ="30 9,11,13,15,17 * * *"
let startLiveReportScriptForClickData_cron_time = "1,31 * * * *"; 
// cron.schedule(cron_time, Afftrack.callAfftrackApi);
// cron.schedule(cron_time, Affise.callAffiseApi);
// cron.schedule(cron_time, Mobikok.callMobikokApi);
// cron.schedule(cron_time, Offerslook.callOfferslookApi);
// cron.schedule(cron_time, Fuseclick.callFuseclickApi);
// cron.schedule(cron_time, Hasoffer.callhasofferApi);
// cron.schedule(cron_time, Hugoffers.callHugoffersApi);
// cron.schedule(cron_time, Offer18.callOffer18Api);
// cron.schedule(cron_time, Orangear.callOrangearApi);
// cron.schedule(cron_time, Orangear_v3.callOrangear_v3Api);
// cron.schedule(cron_time, Youmi.callYoumiApi);
// cron.schedule(cron_time, Vinetool.callVinetoolApi);
// cron.schedule(cron_time, Tabatoo.callTabatooApi);
// cron.schedule(cron_time, Pentamob.callPentamobApi);
// cron.schedule(cron_time, Applift.callAppliftApi);
// cron.schedule(cron_time, Sekomedia.callsekomediaApi);
// cron.schedule(cron_time, Trooperads.callTrooperadsApi);
// cron.schedule(cron_time, DofunApps.callDofunAppsApi);
// cron.schedule(cron_time, Trackier.callTrackierApi);
// cron.schedule(cron_time, Mobiproud.callMobiproudApi);
// cron.schedule(cron_time, Linkgoads.callLinkgoAdsApi);
// cron.schedule(cron_time, Qverseads.callQverseadsApi);
// cron.schedule(cron_time, Occuad.callOccuadApi);
// cron.schedule(cron_time, Megable.callMobxmediaApi);
// cron.schedule(cron_time, Adgagaa.callAdgagaaApi);
// cron.schedule(cron_time, Mobifunadx.callMobifunadxApi);
// cron.schedule(cron_time, Gourdmobi.callGourdmobiApi);
// cron.schedule(cron_time, WhatsCpi.callWhatsCpiApi);
// cron.schedule(cron_time, Appcoachs.callAppcoachsApi);
// cron.schedule(cron_time, Superads.callSuperadsApi);
// cron.schedule(cron_time, Mobivisits.callMobivisitsApi);
// cron.schedule(cron_time, Admedx.callAdmedxApi);
// cron.schedule(cron_time, TrackRC.callTrackrcApi);
// cron.schedule(cron_time, Vortexmedia.callVortexmediaApi);
// cron.schedule(cron_time, Mobimelon.callMobimelonApi);
// cron.schedule(cron_time, FunnyStore.callFunnyStoreApi);
// cron.schedule(cron_time, Zettamobi.callZettamobiApi);
// cron.schedule(cron_time, Echo226.callEcho226Api);
// cron.schedule(cron_time, Promoadx.callPromoadxApi);
// cron.schedule(cron_time, Mobusi.callMobusiApi);
// cron.schedule(cron_time, Mybestclick.callMybestclickApi);
// cron.schedule(cron_time, Cpalock.callCpalockApi);
// cron.schedule(cron_time, Mobisummer.callMobisummerApi);
// cron.schedule(cron_time, Gowide.callGowideApi);
// cron.schedule(cron_time, Artofclick.callArtofclickApi);
// cron.schedule(cron_time, Cityads.callCityadsApi);
// cron.schedule(cron_time, Cpology.callCpologyApi);
// cron.schedule(cron_time, Imocash.callImocashApi);
// cron.schedule(cron_time, Mobrain.callMobrainApi);
// cron.schedule(cron_time, Instal.callInstalApi);
// cron.schedule(cron_time, AppDiscover.callAppDiscoverApi);
// cron.schedule(cron_time, EverflowClient.callEverflowClientApi);
// cron.schedule(cron_time, Dailybestapps.callDailybestappsApi);
// cron.schedule(cron_time, Persona.callPersonaApi);
// cron.schedule(cron_time, Crunchiemedia.callCrunchiemediaApi)
// cron.schedule(cron_time, Vene.callVeneApi)
// cron.schedule(cron_time, Twinkleunion.callTwinkleunionApi);
// cron.schedule(cron_time, Adsplay.callAdsplayApi);
// cron.schedule(cron_time, CollectCent.callCollectCentApi);
// cron.schedule(cron_time, Algambo.callAlgamboApi);
// cron.schedule(cron_time, AdOn.callAdOnApi);
// cron.schedule(cron_time, Apetab.callApetabApi);
// cron.schedule(cron_time, Oneway.callOnewayApi);
// cron.schedule(cron_time, Retail9.callRetail9Api);
// cron.schedule(cron_time, Roidynamic.callRoidynamicApi);
// cron.schedule(cron_time, Avazu.callAvazuApi);
// cron.schedule(cron_time, StarmobMedia.callStarmobMediaApi);
// cron.schedule(cron_time, ResultMedia.callResultMediaApi);
// cron.schedule(cron_time, Mobobeat.callMobobeatApi);
// cron.schedule(cron_time, Agileadnetwork.callAgileadnetworkApi);
// cron.schedule(cron_time, Trackrevenue.callTrackrevenueApi);
// cron.schedule(cron_time, DreamMobi.callDreamMobiApi);
// cron.schedule(cron_time, Clicks9.callClicks9Api);
// cron.schedule(cron_time, Appxigo.callAppxigoApi);
// cron.schedule(cron_time, Auctera.callAucteraApi);
// cron.schedule(cron_time, Appsilon.callAppsilonApi);
// cron.schedule(cron_time, Kpmbro.callKpmbroApi);
// cron.schedule(cron_time, MocaTech.callMocaTechApi);
// cron.schedule(cron_time, Appflood.callAppfloodApi);
// cron.schedule(cron_time, Offershub.callOffershubApi);
// cron.schedule(cron_time, Taptica.callTapticaApi);
// cron.schedule(cron_time, Revlinker.callRevlinkerApi);
// cron.schedule(cron_time, Jinglemobi.callJinglemobiApi);
// cron.schedule(cron_time, Skyworker.callSkyworkerApi);
// cron.schedule(cron_time, Bucksense.callBucksenseApi);
// cron.schedule(cron_time, Totoroadx.callTotoroadxApi);
// cron.schedule(cron_time, Mobeetech.callmobeetechApi);
// cron.schedule(cron_time, Indexmobi.callIndexmobiApi);
// cron.schedule(cron_time, Appleads.callAppleadsApi);
// cron.schedule(cron_time, Feeltapmobi.callFeeltapmobiApi);
// cron.schedule(cron_time, Adbink.callAdbinkApi);
// cron.schedule(cron_time, Trakneo.callTrakneoApi);
// cron.schedule(cron_time, Hehemobi.callHehemobiApi);
// cron.schedule(cron_time, Gadmobe.callGadmobeApi);
// cron.schedule(cron_time, Appicmedia.callAppicmediaApi);
// cron.schedule(cron_time, Informadz.callInformadzApi);
// cron.schedule(cron_time, Addattain.callAddattainApi);
// cron.schedule(cron_time, Addotline.callAddotlineApi);
// cron.schedule(cron_time, Gazet.callGazetApi);
// cron.schedule(cron_time, Curate.callCurateApi);
// cron.schedule(cron_time, Adosiz.callAdosizApi);
// cron.schedule(cron_time, Mobrand.callMobrandApi);
// cron.schedule(cron_time, Pivomob.callPivomobApi);
// cron.schedule(cron_time, Newseed.callNewseedApi);
// cron.schedule(cron_time, Gamespipe.callGamespipeApi);
// cron.schedule(cron_time, Clixsad.callClixsadApi);
// cron.schedule(cron_time, Seanear.callSeanearApi);
// cron.schedule(cron_time, Swaarm.callSwaarmApi);
// cron.schedule(cron_time, Proffcus.callProffcusApi);
// cron.schedule(cron_time, Chestnut.callChestnutApi);
// cron.schedule(cron_time, Sixpush.callSixpushApi);
// cron.schedule(cron_time, Hopemobi.callHopemobiApi);
// cron.schedule(cron_time, Vikingmedia.callVikingmediaApi);
// cron.schedule(cron_time, Mobilink.callMobilinkApi);
// cron.schedule(cron_time, Chestnut.callChestnutApi);
// cron.schedule(cron_time, Sixpush.callSixpushApi);
// cron.schedule(cron_time, Hopemobi.callHopemobiApi);
// cron.schedule(cron_time, Vikingmedia.callVikingmediaApi);
// cron.schedule(cron_time, Mobilink.callMobilinkApi);
// cron.schedule(cron_time, Batmobi.callBatmobiApi);
cron.schedule(cron_time, OfferFetchApi.callApi);
cron.schedule(scrapingScript_cron_time, scrapingScript.startSaveAppIdsScriptForScraping);
cron.schedule(updateScrapingScript_cron_time, updateScrapingScript.startUpdateScraping);

// cron.schedule(cron_time, Cake.callCakeApi);
// currency cron

cron.schedule(update_application_status_time , update_application_status.updateApplicationStatus) ;
cron.schedule("0 0 3 * *", currency.saveCurrency);
cron.schedule(offer_apply_cron_time, applyPlugins.callApplyApi);
// cron.schedule(wOfferAutosync_cron_time, waitingForApprovalofferSync.syncWaitingForApprovalOffer); /// for sync offer  
cron.schedule(wOfferAutosync_cron_time, waitingForApprovalofferSync.sendSyncOfferFilterJobToWorker);
cron.schedule(wOfferAutosync_cron_time2, waitingForApprovalofferSync2.sendSyncOfferFilterJobToWorker);
// cron.schedule( offersCountByAppId_cron_time , offersCountByAppId.updateApplicationDetailsByAppIds);
cron.schedule(report_cron_time, reportsCron.startCronScript);
cron.schedule(wishListUpdateTime, wishListUpdate.findConvertingPackages);
cron.schedule(wishListFlushTime, wishListFlush.filterWishlist);
cron.schedule(pkgSummaryGenTime, PackageIdSummary.createAppIdSummary);
// cron.schedule(offerDeleteTime, OfferDelete.deleteInactiveOffers);
cron.schedule("*/10 * * * *", UpdateOffersCountInRedis.saveOffersCountInRedis);
// cron.schedule(dashboard_cron_time, dashboard.startDashboardScript);
cron.schedule( dashboard_live_cron_time , live_dashboard_Script.runScript) ;
// cron.schedule(dashboard_cron_time, dashboard.startPublisherDashboardScript);
// cron.schedule("*/10 * * * *", liveReportScript.startLiveReportScript);
cron.schedule(`*/${EWT_WEBHOOK_TIME_GAP} * * * *`, ewtScript.runScript);
// cron.schedule(autoBlock_cron_time, autoBlockOffer.runAutoBlock);
cron.schedule(advOfferstats_CronTime,advOfferScript.getData)
cron.schedule(autoApplyAndPushToWebhook_cron_time , AutoApplyAndPushToWebhook.applyAndPushToWebhookFromJumbo);
cron.schedule(startLiveReportScriptForClickData_cron_time, startLiveReportScriptForClickData.startLiveReportScript); // when rabbitmq failed from ninja, this script to correct report.
